---
- copy:
    src: bashrc/.bashrc_{{ item.name }}
    dest: /home/{{ item.name }}/.bashrc
    owner: "{{ item.name }}"
    group: "{{ item.groups }}"
    mode: 0644
    with_items: "{{ users_list }}"
    tags: users_files