---
- name: SSH KEY | variabilise personnal keys
  include_vars: "vars/main.yml"
  no_log: true

- name: SSH KEY | keys
  include_vars: "files/secret.yml"
  no_log: true
  
- include: deploy.yml
  tags: users

- include: import_files.yml
  tags: [users,users_files]
