---
 pre-task:
    - name: Update cache repos
    apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Install NTP
      apt: package=ntp state=present update_cache=yes
      tags: ntp

    - name: Copy over the NTP configuration
      template: src=ntp.conf.j2 dest=/etc/ntp.conf
    notify:
      - restart ntp
      - name: ensure ntp is running
    service: name=ntp state=started
      tags: ntp
