users_list:
  - { name: 'jeremie', group1: 'devops', group2: 'users', key: 'public_keys/jeremie', bash_file: 'bashrc/.bashrc_jeremie' }
  - { name: 'julien', group1: 'devops', group2: 'users', key: 'public_keys/julien', bash_file: 'bashrc/.bashrc_julien' }

groups_list:
  - devops

sudoers_list:
  - { regexp: '^%devops', line: 'devops ALL=(ALL) NOPASSWD: ALL' }